### ISSUE TITLE
Documentation is wrong - use `path` instead of `root` in options

### ISSUE THREAD

**Issue by paambaati** [strawbrary/koa-nunjucks-2#1]
Just a heads up - your documentation is a little out of date; the default options should specify `path` instead of `root`.

```
app.context.render = koaNunjucks({
  autoescape: true,
  ext: 'html',
  path: path.join(__dirname, 'views')
});
```

Do you want me to submit a PR?

**Comment by strawbrary** [comment]
I'll take care of it, thanks for reporting.
