### ISSUE TITLE
Add filter with koa 2

### ISSUE THREAD

**Issue by ghost** [strawbrary/koa-nunjucks-2#10]
Is there a way to use addFilter() with koa2?

**Comment by strawbrary** [comment]
Yes, you can pass the `configureEnvironment` option with a function that will receive the Nunjucks environment. See the example [here](https://github.com/strawbrary/koa-nunjucks-2/tree/v3.x#extending-nunjucks).

**Comment by ghost** [comment]
Ok. thanks. And sorry, I should look more carefully at the docs before open such a stupid issue.

**Comment by strawbrary** [comment]
No problem. 🙂
