### ISSUE TITLE
How to use with pre-compiled template?

### ISSUE THREAD

**Issue by Extarys** [strawbrary/koa-nunjucks-2#27]
Hi there!
In the nunjucks documentations, it's written that you should pre-compile your templates before distribution/production.

I just did to test it, but this package doesn't render the js properly.

How should we setup this?

Thanks

**Comment by strawbrary** [comment]
Hi Extarys. I believe the precompiled option only applies if you are using Nunjucks on the browser. When using Nunjucks on Node.js, it compiles it once, then will serve the cached version for all subsequent requests (unless you set [noCache](https://mozilla.github.io/nunjucks/api.html#configure) to true). So as long as you're only using your templates server-side, you shouldn't need to worry about precompiling. Hope that helps.

**Comment by Extarys** [comment]
Ohhh I see thank you very much!
