### ISSUE TITLE
Use njk as the default extension 

### ISSUE THREAD

**Issue by whatyoubendoing** [strawbrary/koa-nunjucks-2#8]
As per nunjucks recomendation https://github.com/mozilla/nunjucks/blob/master/CHANGELOG.md + upgrade nunjucks.

**Comment by strawbrary** [comment]
I've changed the default extension on the `v3.x` branch to `.njk`. I'll keep this issue open as a reminder to update Nunjucks since their `v3` is still in development. Thanks!

**Comment by strawbrary** [comment]
Updated to v3 a while ago and forgot to close this...
