### ISSUE TITLE
Example for 3.x branch?

### ISSUE THREAD

**Issue by felixsanz** [strawbrary/koa-nunjucks-2#9]
Please!

**Comment by strawbrary** [comment]
Hello, there's an example in the [v3.x branch REAME](https://github.com/strawbrary/koa-nunjucks-2/tree/v3.x#example).

**Comment by felixsanz** [comment]
I'm struggling with this for hours and probably is an easy one, but i can't catch it.

Just having `import nunjucks from 'koa-nunjucks-2'` gives me this error:

```
  return async (ctx, next) => {
               ^

SyntaxError: Unexpected token (
```

I'm using babel-node with this .babelrc file: `{ "presets": ["es2015", "stage-3"] }`

Can you give me a hand please?

Other middleware like `app.use(async (ctx, next) => {})` is working, so this looks like babel is not parsing node_modules ?

**Comment by strawbrary** [comment]
Yeah sorry there was an error in `3.0.0-alpha.1`, I published it without running it through Babel. Try updating to `3.0.0-alpha.2` and see if that fixes the error for you.

**Comment by felixsanz** [comment]
Oh damnit! xD Thanks

btw: push it to latest in npm?

**Comment by strawbrary** [comment]
I'm going to keep `v3.x` on the `next` tag until koa promotes their `v2.x` to the `latest` tag.

**Comment by felixsanz** [comment]
thats what i mean. i used the next tag and i got 3.0.0-alpha.1

**Comment by strawbrary** [comment]
It was probably published after you installed so you should be able to wipe your `node_modules` directory and run `npm install` and it will pull down `3.0.0-alpha.2`.
